### ISSUE TITLE
The reading  for previous date can be cleared to allow sync between 

### ISSUE THREAD

**Issue by AnnCherianA** [Bridgeconn/VachanOnline-v2#103]
The reading for the previous date selected does not clear if the user switches to a different month or year ie The references if displayed only if the user selects a date would be better. In that case there would be a sync between the reading displayed and the display on the calendar . 

Screenshot for current date

![currentdate](https://github.com/Bridgeconn/VachanOnline-v2/assets/132653333/82aefcc5-2b07-499e-a9d3-4f7cf26e2605)

screenshot for the  changed month and year

![different date](https://github.com/Bridgeconn/VachanOnline-v2/assets/132653333/d636c3d4-5b36-49ba-8deb-d018fe7767b8)

As discussed in the Vachan Meeting on 27/07/2021, since this is not a blocker for 1.3. 0 , it can be taken up for future releases.

**Comment by VineethaVi** [comment]
@AnnCherianA  uploaded the screenshot for the issue description.

**Comment by VineethaVi** [comment]
This is the screenshot

![update](https://github.com/Bridgeconn/VachanOnline-v2/assets/132653333/69a36a45-6fa1-4522-8cb7-11bdc4157f01)

This is the behaviour. If we select month , year along with the date , the reading plan changes for the selected date.

closing this issue as we discussed.
