### ISSUE TITLE
Verse selection to be cleared on switching to a different icon

### ISSUE THREAD

**Issue by AnnCherianA** [Bridgeconn/VachanOnline-v2#117]
After selecting verses of a chapter eg Matthew 1:2,3,4  , on switching to reading plan andselecting references (eg Revelations 1)  in the reading plan, it would navigate to the book mentioned in the Reading plan (Revelations)  ,but the verses selected before opening the Reading plan ie 1,2,3 of Revelations would still be selected. The verse selection is to be cleared on switching to Reading plan (medium)

**Comment by AnuMonachan** [comment]
Fixed this issue in 1.3.2 release

**Comment by AnnCherianA** [comment]
@LijuJacob08  please verify this issue on the latest release and update the status

**Comment by LijuJacob08** [comment]
Tested the issue it's been fixed, attaching the screen recording and  moving to done.

https://user-images.githubusercontent.com/93033055/148778390-15ec27f1-335f-4cb2-9f5d-c6285a71c296.mp4
