### ISSUE TITLE
Infographics : Alert (not available) to display on switching to icons in the right menu

### ISSUE THREAD

**Issue by AnnCherianA** [Bridgeconn/VachanOnline-v2#121]
For languages with no Infographics the information  to the user that  says infographics is not available  for a particular book does not display on switching to  icons  in the right menu -Commentary or Dictionary. This message loads when we select the language  from the book selector

**Comment by JesniJ** [comment]
Completed testing and the message " infographics not available for particular languages" is showing even after switching from commentaries and dictionary. As discussed moving moving this issue to done.
