### ISSUE TITLE
Print chapter-Save option

### ISSUE THREAD

**Issue by AnnCherianA** [Bridgeconn/VachanOnline-v2#126]
![image](https://user-images.githubusercontent.com/12570574/140505135-0c66a8e6-8d2e-402a-86ff-6b4159f3cab0.png)

1 - To print a chapter open the settings popover and click on print 
2 - This opens a dialog with 2 checkboxes to print notes and highlights on the page. Click print button to print or download the chapter or cancel to go back to reading page.

**Comment by AnnCherianA** [comment]
Tested chapter print/save feature .Works fine .
The notes and highlights are well implemented.
- The file length is too long
- Its name vachan online -Indian Bible study site can be renamed to Vachan Online <book> <chapter >
- The netlify site shows in the downloaded pdf. Is this necessary to show the netlify site to the user. 
![image](https://user-images.githubusercontent.com/74647279/140019183-e365f7e2-e082-4526-9300-d42ae06d9c87.png)

**Comment by LijuJacob08** [comment]
Noticed that if any verse is in selected state while saving the PDF  , it will reflect as selected in the saved copy as well.

![image](https://user-images.githubusercontent.com/93033055/140505239-21ea5705-176c-49ab-b153-437fe0c52d99.png)

**Comment by LijuJacob08** [comment]
verified that the pdf name and selected verse highlighted issue are fixed now.

![image](https://user-images.githubusercontent.com/93033055/140514694-a72ddda2-030e-43dc-85a0-9d67a866a997.png)

**Comment by LijuJacob08** [comment]
adding on more  to the list:-

Right on the screen is properly justified
![image](https://user-images.githubusercontent.com/93033055/140754405-30a7dc7c-4143-4959-ab5f-ccd0bdc84a91.png)
 

But for  PDF ,right side not properly justified
![image](https://user-images.githubusercontent.com/93033055/140754457-a999982d-5f25-476b-9ea5-267a09b2e2fe.png)

**Comment by AnnCherianA** [comment]
@LijuJacob08 please update the status of this issue and move it.

**Comment by LijuJacob08** [comment]
Right side in the pdf is now properly justified, attaching the screenshot for the same.  Hence moving to done.

![image](https://user-images.githubusercontent.com/93033055/148772182-1dafafce-2d16-4f2f-9340-c11253a90141.png)
