### ISSUE TITLE
Show full language name in landing page language dropdown

### ISSUE THREAD

**Issue by AnuMonachan** [Bridgeconn/VachanOnline-v2#136]
![image.png](https://images.zenhubusercontent.com/602cd08fc23cb87f11885c62/4cec675c-5f1d-4755-a90b-7debe0a577cf)

**Comment by LijuJacob08** [comment]
had tested it, looks good ,hence moving to done.

Attaching the screenshots for the same.

![Screenshot from 2022-01-09 15-02-38](https://user-images.githubusercontent.com/93033055/148677072-a51c136c-166f-4dc6-94c8-93e391598cd0.png)

![Screenshot from 2022-01-09 15-03-06](https://user-images.githubusercontent.com/93033055/148677079-385e0e80-0588-48f7-8adb-dfaffb429b37.png)

![Screenshot from 2022-01-09 15-04-59](https://user-images.githubusercontent.com/93033055/148677084-3b8aa358-34ba-4c63-8e8f-c91cf036c7d5.png)
