### ISSUE TITLE
hide verse label in commentary

### ISSUE THREAD

**Issue by AnuMonachan** [Bridgeconn/VachanOnline-v2#185]
Hide verse label in commentary where it is already present (eg. ESV Global Study Bible) from metadata, add VerseLabel tag in metadata

![MicrosoftTeams-image.png](https://images.zenhubusercontent.com/602cd08fc23cb87f11885c62/b4b202df-637c-40cd-9d86-0a57d27ae668)

**Comment by LijuJacob08** [comment]
hi ,
had tested the ESVGSB , results were as expected.
attaching the screenshot for the same.
![image](https://user-images.githubusercontent.com/93033055/171855159-b979756b-f82b-4b3f-9b44-1619fd239b88.png)

hence,moving to done.
