### ISSUE TITLE
Selected verse is hidden by the horizontal bar

### ISSUE THREAD

**Issue by SeemaNandihal** [Bridgeconn/VachanOnline-v2#223]
When we browse through the Bible in VachanGo.1.3.6-alpha.3.apk, the selected verse is hidden behind the horizontal bar; we must scroll down to see it.  According to the screenshot attached, the selected verse is 1 Kings 7:4, while the screen shows 1 Kings 7:5.
![1665653319911](https://user-images.githubusercontent.com/109131516/195569394-08d6d47b-aea8-4aeb-a211-94857686368b.jpg)

**Comment by VineethaVi** [comment]
This issue supposed to under VachanGo. There is already existing issue for same thing. So, closing this issue opened in Vachan.
