### ISSUE TITLE
Show commentary images in popup

### ISSUE THREAD

**Issue by AnuMonachan** [Bridgeconn/VachanOnline-v2#240]
Show commentary images in popup like infographics with zoom in/out feature to accommodate higher resolution images also 

Issues with images mentioned in - [ESV Images List](https://bridgeconn-my.sharepoint.com/:x:/p/ann_cherian/EWf4Wo0kjBBGqZgoFOREySoBlNSpghR2TcYCfujQ6bbmBw?e=JyA0uP)

**Comment by VineethaVi** [comment]
Test Result : Tested on Website

Selected English ESV from language dropdown
Selected Matthew 1 from book dropdown
Opened the reading page
Selected commentary from right side bar
Opened the commentary
Clicked the image , it showing in a pop up

It is working fine and testing done on chrome.


![commentary popup](https://github.com/Bridgeconn/VachanOnline-v2/assets/132653333/89d23b16-a3a9-41eb-b0c7-2cf4eda471c1)

**Comment by VineethaVi** [comment]
Test Result : Tested on Mobile browser
Selected English ESV from language dropdown
Selected Matthew 1 from book dropdown
Opened the reading page
Selected commentary from the bottom
Opened the commentary
Clicked the image , it showing in a pop up

It is working fine and testing done on google chrome in mobile.

![MicrosoftTeams-image (6)](https://github.com/Bridgeconn/VachanOnline-v2/assets/132653333/f06a48f7-2ad1-45d0-b9fd-13f05a6af63d)

**Comment by VineethaVi** [comment]
Moving to QA review

**Comment by VineethaVi** [comment]
As discussed in VO standup, most of the ESV are in Review. Only English ESV is passed. 
So, Testing done on commentary images in  English ESV

**Comment by VineethaVi** [comment]
Moving to Done.
