### ISSUE TITLE
Bottom Bar  for mobile view

### ISSUE THREAD

**Issue by Poojanavgurukul** [Bridgeconn/VachanOnline-v2#243]
![bottom bar](https://user-images.githubusercontent.com/34941343/204453382-acfab5a4-479d-4152-a7e1-365dbbcae7ed.png)

**Comment by AnnCherianA** [comment]
@vineetha please test this issue and share the result.

**Comment by JesniJ** [comment]
The test results are  verified and those results were documented clear with screenshots , therefore moving this issue to done.
