### ISSUE TITLE
Commentary Mobile View

### ISSUE THREAD

**Issue by Poojanavgurukul** [Bridgeconn/VachanOnline-v2#244]
split the commentary view 
![commentary](https://user-images.githubusercontent.com/34941343/204455399-d1ac97cc-2388-4ee5-a780-fd127a4f992e.png)

**Comment by AnnCherianA** [comment]
@JesniJ please test this issue and  share the result

**Comment by JesniJ** [comment]
Testing done in chrome browser and verified that commentary in mobile view is working correctly . If the user selects commentaries page will be splitt in two . Top portion shows the bible and commentaries in bottom.

As its working as expected moving this issue to done.
