### ISSUE TITLE
Search mobile View

### ISSUE THREAD

**Issue by Poojanavgurukul** [Bridgeconn/VachanOnline-v2#245]
![searchView](https://user-images.githubusercontent.com/34941343/204457166-90633226-ed42-4af1-8046-e0a250c5c1c7.png)

**Comment by AnnCherianA** [comment]
@vineetha please test this issue and share the result.

**Comment by AnnCherianA** [comment]
@VineethaVi please test this issue and share the result

**Comment by VineethaVi** [comment]
Test Result
1.selected the book Romans in English ESV
2.selected the search icon from bottom bar
3.searched the word Gospel
It is working fine and tested on Google Chrome in mobile
![Screenshot_2023-05-08-10-00-05-03_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/132653333/236796963-0289f4d6-560f-4b1a-9307-7624e52c4914.jpg)
Other checked book
1.selected the book John in English ESV
2.selected the search icon from bottom bar
3.search the word God
4.selected the language Hindi
5.changed the bible verses English to Hindi
Search box is already still in that page not changed.
It is working fine and tested on Google Chrome in mobile
![Screenshot_2023-05-08-10-03-21-55_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/132653333/236798145-7bf839bb-f21d-4892-9f5b-ce2ec11e0023.jpg)

**Comment by VineethaVi** [comment]
Moved to QA review

**Comment by JesniJ** [comment]
The test results are  verified and those results were documented clear with screenshots , therefore moving this issue to done.
