### ISSUE TITLE
Drawer Mobile View

### ISSUE THREAD

**Issue by Poojanavgurukul** [Bridgeconn/VachanOnline-v2#247]
![drawer](https://user-images.githubusercontent.com/34941343/204485744-02284702-d961-46bf-992a-2c68e5fc3e58.png)

**Comment by AnnCherianA** [comment]
@selvabenz  please test this issue and share the result

**Comment by AnnCherianA** [comment]
@VineethaVi please test this issue and share the result.

**Comment by VineethaVi** [comment]
Test Result
1.selected the book John
2.selected the menu bar
Not seened mail id and sign out button in menu bar.
 Tested on Google Chrome in mobile
![IMG_20230508_164545](https://user-images.githubusercontent.com/132653333/236811322-82dcc031-6d3d-4fc0-8966-35602342af43.jpg)
Noticed: mail id and sign out is in the profile icon in the top bar
![IMG_20230508_164630](https://user-images.githubusercontent.com/132653333/236811739-34386b9a-54b7-45cc-9665-420e391293ae.jpg)

**Comment by VineethaVi** [comment]
Moving to QA review

**Comment by JesniJ** [comment]
The test results and observation clearly written with screenshots therefore moving this issue to done.
