### ISSUE TITLE
Mobile view for Bible Menu Bar

### ISSUE THREAD

**Issue by Poojanavgurukul** [Bridgeconn/VachanOnline-v2#248]
![subToolbar.png](https://images.zenhubusercontent.com/60f15129e0d1f4ef8c7cb022/062b2fee-a49a-4b83-8b3a-805cb3bf034e)

**Comment by VineethaVi** [comment]
Test Result
1.Selected the book John in Hindi IRV
2.Loaded the page 
In Bible menu bar audio icon is replaced in the printer icon.
Tested on Google Chrome in mobile
![IMG_20230508_165943](https://user-images.githubusercontent.com/132653333/236814710-709ee902-8f22-4932-9370-3f1f791f6e9c.jpg)
 Other checked:
Rotated the phone
1.Selected the book John in Hindi IRV
2.Loaded the page 
In Bible menu bar included the icon printer and audio.


![IMG_20230508_165917](https://user-images.githubusercontent.com/132653333/236815567-02d311aa-fc1b-4dad-8076-5b48adf07b67.jpg)
Tested on Google Chrome in mobile

**Comment by VineethaVi** [comment]
Moving to QA review

**Comment by JesniJ** [comment]
The test resuts were written proper with screenshots therefore moving this issue to done .
