### ISSUE TITLE
Sign In- Annotation Bar

### ISSUE THREAD

**Issue by SeemaNandihal** [Bridgeconn/VachanOnline-v2#264]
If the user has not logged in, the annotation bar should not show up.

**Comment by AnnCherianA** [comment]
@JesniJ  please test and share the result

**Comment by Poojanavgurukul** [comment]
bottom bar of color palate and note icon is  coming if user is not sign in

**Comment by AnnCherianA** [comment]
@JesniJ please include screenshots.

**Comment by AnnCherianA** [comment]
@Revant thanks for sharing this information. 
As per the discussion with Revant yesterday,  since the annotation bar  would not show on the bottom or select the verse when the user is logged in, moving to Done
