### ISSUE TITLE
Reading plan date

### ISSUE THREAD

**Issue by SeemaNandihal** [Bridgeconn/VachanOnline-v2#265]
![Image](https://user-images.githubusercontent.com/34941343/216236425-6ee39f5d-8199-4890-8735-ec2b8e22e2c2.png)

The date of the reading plan should be on the same line as the heading.

**Comment by AnnCherianA** [comment]
@vineetha please test this issue and share the result

**Comment by AnnCherianA** [comment]
@VineethaVi please test the issue and share the result

**Comment by VineethaVi** [comment]
Test Result
1.selected the book 1corinthians chapter 1 in English ESV
2.selected the reading plan icon from the bottom bar 
The date of the reading plan is on the same line as the heading.
It is working fine and tested on Google Chrome in mobile

![IMG_20230508_160009](https://user-images.githubusercontent.com/132653333/236801947-d4b5d6c4-9db6-4ea1-a4a0-c7caf3b42436.jpg)

**Comment by VineethaVi** [comment]
Moved to QA review

**Comment by JesniJ** [comment]
The test results is verified and those results were documented clear with screenshots , therefore moving this issue to done.
