### ISSUE TITLE
Reading Plan date dropdown

### ISSUE THREAD

**Issue by SeemaNandihal** [Bridgeconn/VachanOnline-v2#266]
![Image](https://user-images.githubusercontent.com/34941343/216236482-171cf269-d39c-4a94-8181-f617b88fa469.png)

On clicking the close button, the date should be cleared.

**Comment by AnnCherianA** [comment]
@JesniJ please test this issue and share the result.

**Comment by JesniJ** [comment]
Testing done in chrome browser. 
Steps followed in testing 
select reading plan ---> choose any date ----> close ------->> choosen date is cleared and present date will set  when user selects the reading plan next time. 

Here am attaching the screen recording here for the same . 

https://user-images.githubusercontent.com/102143707/236230248-ce7a6cda-5c53-44f3-8fd0-8f5b15c1ba5f.mp4

Thus moving this issue to done.
