### ISSUE TITLE
Bottom bar icons

### ISSUE THREAD

**Issue by SeemaNandihal** [Bridgeconn/VachanOnline-v2#267]
![Image](https://user-images.githubusercontent.com/34941343/216236589-c741e710-1d6b-407e-961d-4bb21f36ff4d.png)

On hovering over the icons at the bottom bar, the selected icon should highlight.

**Comment by AnnCherianA** [comment]
@VineethaVi please test this issue and share the result.

**Comment by VineethaVi** [comment]
Test Result
1.selected the book John chapter 1in Hindi IRV
2.opened the page
3.selected the commentary icon from bottom bar.
On hovered over the icons at the bottom bar, the selected icon highlighted.
It is working fine and tested on Google Chrome in mobile.
![IMG_20230509_142602](https://user-images.githubusercontent.com/132653333/237047292-a708e03c-5d09-47bb-b448-51e3da3c3161.jpg)

**Comment by JesniJ** [comment]
The Actual requirement is when user selects(not hover) an icon from the bottom bar , that selected icon will be shown as highlighted . 
Test results had updated with screenshots so am moving this issue to done.
