### ISSUE TITLE
Text beside Icon in drawer

### ISSUE THREAD

**Issue by SeemaNandihal** [Bridgeconn/VachanOnline-v2#268]
When we select the text beside the icons in the drawer, it should redirect to the relevant page.

**Comment by AnnCherianA** [comment]
@vineetha please test this issue and share the result.

**Comment by VineethaVi** [comment]
Test Result
step1:selected the book Psalms chapter1 in English ESV
step2:selected the menu bar in bottom
step3:selected the text beside the icon commentary
step4:redirected to the page commentary
Other checked icon
step1:selected the book Psalms chapter1 in English ESV
step2:selected the menu bar in bottom
step3:selected the text beside the icon video
step4:redirected to the page video
![Screenshot_2023-05-08-psc](https://user-images.githubusercontent.com/132653333/236699826-c3eda10f-986f-40ea-9cf2-697e6025f5a4.jpg)
![Screenshot_2023-05-08-v](https://user-images.githubusercontent.com/132653333/236699856-ee37afa7-3674-420a-a87c-78670c7e544b.jpg)
Other book checked
step1:selected the book Romans chapter1  in Hindi 
step2:selected the menu bar in bottom
step3:selected the text beside the icon infographic
step4:redirected to the page infographic
![Screenshot_2023-05-08-info](https://user-images.githubusercontent.com/132653333/236700166-e6430a49-12ac-476a-af40-76b3eeccb85a.jpg)

 the tested issues are working fine and tested on google chrome in mobile.

**Comment by VineethaVi** [comment]
moving to QA review

**Comment by JesniJ** [comment]
The test results are verified and those results were documented clear with screenshots , therefore moving this issue to done.
