### ISSUE TITLE
Drawer's current view

### ISSUE THREAD

**Issue by SeemaNandihal** [Bridgeconn/VachanOnline-v2#270]
Once we choose the icons, the drawer's current view should not change.

**Comment by AnnCherianA** [comment]
@vineetha please test this issue and share the result

**Comment by AnnCherianA** [comment]
@VineethaVi  please test this issue and share the result

**Comment by VineethaVi** [comment]
I didn't understand. Can you share screenshot?

**Comment by AnnCherianA** [comment]
@VineethaVi please have a discussion with Pooja and understand the requirement

**Comment by VineethaVi** [comment]
Test Result
1.selected the book Exodus chapter 1 in English ESV
2.selected the menu icon in bottom
3.selected the infographic icon
4.opened the infographic
5.selected the menu icon from bottom
Existed the current page infographic.
It is working fine and tested on Google Chrome in mobile.
![IMG_20230509_123314](https://user-images.githubusercontent.com/132653333/237021541-243ab919-3ad2-4671-948e-469fc5f0553d.jpg)
 
Other checked:
1.selected the book Exodus chapter 1 in English ESV
2.selected the menu icon in bottom
3.selected the audio icon
4.opened the audio 
5.selected the menu icon from bottom
Existed the current page audio.
It is working fine.
![IMG_20230509_123838](https://user-images.githubusercontent.com/132653333/237021957-e2a9e087-ef77-4cc2-8d0d-5fc6dcd0b874.jpg)

**Comment by VineethaVi** [comment]
Moving to QA review

**Comment by JesniJ** [comment]
As the test results are clearly written with screenshots  , moving this issue to done

**Comment by JesniJ** [comment]
Moving this issue back to Qa review to document the exact requirement of the issue .

**Comment by JesniJ** [comment]
Issue Description : If the user chooses any option from the bottom menu  the selected feature is loaded . Again if the user selects the menu button background page was showing buffering icon and not showing the previously loaded page . Now its showing the previously loaded page in the background , when the user clicks the bottom menu bar.

![WhatsApp Image 2023-05-09 at 7 07 50 PM (1)](https://github.com/Bridgeconn/VachanOnline-v2/assets/102143707/5e04c424-876a-4057-823b-9e4aee058949)

![WhatsApp Image 2023-05-09 at 7 07 50 PM](https://github.com/Bridgeconn/VachanOnline-v2/assets/102143707/2da97ed1-ea95-4947-803d-fee7f1037fb1)
 
As the requirement is documented moving this issue to done .
