### ISSUE TITLE
Drawer close button

### ISSUE THREAD

**Issue by SeemaNandihal** [Bridgeconn/VachanOnline-v2#271]
![Image](https://user-images.githubusercontent.com/34941343/216236810-a0c1576d-0917-4e76-bc22-8f6c0952e995.png)

Remove the drawer close button as this is not required.

**Comment by AnnCherianA** [comment]
@JesniJ please test this issue and share the result

**Comment by AnnCherianA** [comment]
@vineetha please test this issue and share the result

**Comment by VineethaVi** [comment]
Test Result
step1:selected the NT book Mark chapter1
step2:selected the menu bar in bottom
step3: opened without containing close button
It is working fine and tested on chrome browser in mobile
![Screenshot_2023-05-08-00](https://user-images.githubusercontent.com/132653333/236697438-8e0d3801-3229-47bf-a780-859a4ca1c3c7.jpg)
Other language checked
step1:selected the book Mark1 in Dogri Language
step2:selected the menu bar in bottom
step3: opened without containing close button
It is also working and tested on chrome in mobile
![Screenshot_2023-05-08](https://user-images.githubusercontent.com/132653333/236697542-411ef783-f480-4af2-8be3-f32b48de499e.jpg)

**Comment by VineethaVi** [comment]
moving to QA review

**Comment by AnnCherianA** [comment]
Moving back to QA review

**Comment by JesniJ** [comment]
The test results were  documented clear with proper screenshots , therefore moving this issue to done.
