### ISSUE TITLE
Commentary in single pane

### ISSUE THREAD

**Issue by SeemaNandihal** [Bridgeconn/VachanOnline-v2#272]
![Image](https://user-images.githubusercontent.com/34941343/216237044-98207497-ca2b-40aa-ae70-85eac308cdb4.png)

When we select the commentary icon in the drawer, the page should load in a single pane and the user should be able to choose the Bible books from the drop-down.

**Comment by AnnCherianA** [comment]
@JesniJ   please test this issue and share the result

**Comment by JesniJ** [comment]
Steps followed in testing :
1. Select any book and  click read in landing page 
2. select menu icon in the bottom
3. choose commentaries from the drawer
4. Commentary is loaded in single pane and the user is able to the change the language ,book and chapter
attaching screenshot for the reference
![WhatsApp Image 2023-05-09 at 9 11 23 PM](https://github.com/Bridgeconn/VachanOnline-v2/assets/102143707/17a0cf6a-6e05-427b-a9e3-3c2262cc8a60)

**Comment by JesniJ** [comment]
Testing completed and results updated with screenshot, therefore moving this issue to done
