### ISSUE TITLE
ISL singe pane

### ISSUE THREAD

**Issue by SeemaNandihal** [Bridgeconn/VachanOnline-v2#273]
![Image](https://user-images.githubusercontent.com/34941343/216237229-b05d0858-6372-4d40-9ae6-6998448d1347.png)

When we click the ISL icon in the drawer, the page should load only a single pane.

**Comment by AnnCherianA** [comment]
@vineetha please test this issue and share the result.

**Comment by VineethaVi** [comment]
Test Result
step1: selected the book Genesis chapter1 in English ESV
step2: selected the ISLV from menu bar in bottom
step3: page loaded in single pane
It is working fine and tested on chrome browser in mobile
![Screenshot_2](https://user-images.githubusercontent.com/132653333/236695967-fd59dbef-6753-4200-8384-7434f50626b9.jpg)
observation
step1: selected the book Genesis chapter1 in English ESV
step2: selected the ISLV from top bar
step 3: page loaded in double pane
![Screenshot_3](https://user-images.githubusercontent.com/132653333/236696078-2cba91d2-fc7f-41a1-b579-b4afe4cd4cc4.jpg)

**Comment by VineethaVi** [comment]
moving to QA review

**Comment by JesniJ** [comment]
As the test results and observation is clearly written with screen shots, moving this issue to done
