### ISSUE TITLE
Edit and reference option in Notes

### ISSUE THREAD

**Issue by Poojanavgurukul** [Bridgeconn/VachanOnline-v2#276]
![Image](https://user-images.githubusercontent.com/34941343/216237870-4bbf0088-fd78-4564-96f9-bdf193a372c5.png)

Add a note edit icon that, when clicked, opens the note editor in mobile view or the reference page

**Comment by AnnCherianA** [comment]
@JesniJ  please test this issue and share the result.

**Comment by AnnCherianA** [comment]
@vineetha please test this issue and update the result

**Comment by VineethaVi** [comment]
Test

**Comment by VineethaVi** [comment]
Test Result
steps taken:-
selected OT book Joshua chapter 1 in English ESV
created the notes
selected the notes icon from bottom bar menu
note editor and delete option
edited the note and saved
It is working fine and tested on chrome browser in mobile.
Noticed : Notes icon in top bar only for adding notes.
![Screenshot_7](https://user-images.githubusercontent.com/132653333/236458606-f8787f03-1291-4091-ab48-35034fe07961.jpg)
added  note 'testing' 
![Screenshot_2023-05-05-10-20-22-51_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/132653333/236458944-c6e05a5f-2ce9-4029-b9e6-c95c8a016575.jpg)
edited testing to tested
![Screenshot_4](https://user-images.githubusercontent.com/132653333/236459414-a04a7659-3dd0-45b5-90af-e74c1864b762.jpg)

**Comment by VineethaVi** [comment]
moving to QA review

**Comment by AnnCherianA** [comment]
@VineethaVi  Did you check whether you are able to add notes

**Comment by VineethaVi** [comment]
@AnnCherianA 
No. I will check the add notes in the note icon. I checked only selected bible verses are added to notes and editing that notes.

**Comment by VineethaVi** [comment]
Test Result
Step 1: selected the book mark verses 1:1 in English 
step2 :selected the adding notes
Step3:created the notes
It is working fine and tested on Google Chrome in mobile 

![Image](https://user-images.githubusercontent.com/132653333/236717443-9f9ea6e7-96b3-4532-955d-13fcd569552e.jpg)
![Image](https://user-images.githubusercontent.com/132653333/236717442-2c39e7e7-8b16-481f-ae45-3f2ef6249976.jpg)

**Comment by VineethaVi** [comment]
Moved to QA review

**Comment by JesniJ** [comment]
As the test results are written clear with screenshots , moving this issue to done
