### ISSUE TITLE
bottom menu note icon size

### ISSUE THREAD

**Issue by Poojanavgurukul** [Bridgeconn/VachanOnline-v2#277]
![Image](https://user-images.githubusercontent.com/34941343/216238020-280a9963-9d0b-4685-ad6e-593c53c01992.png)

Make the note icon same as the highlights color palette in the bottom menu

**Comment by AnnCherianA** [comment]
@JesniJ  please test this issue and share  the result

**Comment by selvabenz** [comment]
@AnnCherianA This issue is working as expected therefore moving the issue to done.

**Comment by AnnCherianA** [comment]
> @selvabenz could you please get on a call with Pooja and try to understand this issue. Once the requirement is clear, please document it here. You may proceed to test after that.

@selvabenz Benz,  thanks for the test result. Please go through the above comemnt.  Please document the requirement here .Did you have a discussion with Pooja.

**Comment by AnnCherianA** [comment]
Also, please share screenshots also once the testing is done.

**Comment by selvabenz** [comment]
The Screenshot of the result

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/121541505/235641893-5316870a-a50d-48e7-962b-36314742ce01.png)

**Comment by selvabenz** [comment]
Size of the note icon in the bottom menu looks the same as the highlight icons. Therefore moving the issue to done.

**Comment by JesniJ** [comment]
Issue Description : Notes icon size was smaller than the highlight icon, it is changed to same size as the highlights icons. 

Test Results had already shared by selvabenz , Therefore moving this issue to done.
