### ISSUE TITLE
 unnecessary spaces exists in between words in bible reading page 

### ISSUE THREAD

**Issue by JesniJ** [Bridgeconn/VachanOnline-v2#301]
For the languages Kannada (IRV) , Malayalam (IRV,ERV), Tamil (IRV), Telugu (IRV) In bible reading page  unnecessary spaces exists in-between words .

Am adding screen shots for the reference
![Mal_ERV](https://user-images.githubusercontent.com/102143707/236384308-eac76691-292e-4cd5-bc9f-76b8e6ff457f.jpeg)
![kannada_IRV](https://user-images.githubusercontent.com/102143707/236384320-b73739e9-6fe1-4c93-8bd7-019155ae7772.jpeg)
![Tamil_IRV](https://user-images.githubusercontent.com/102143707/236384334-984b1693-7c17-4095-9101-ac23fdf3b9c8.jpeg)
![Telugu_IRV](https://user-images.githubusercontent.com/102143707/236384342-a062f518-b44c-4db7-9ba6-bc2fa4f86fff.jpeg)

**Comment by AnnCherianA** [comment]
@JesniJ please mention where you observed this. The platform

**Comment by JesniJ** [comment]
It is in mobile browser , i have added the mobile browser label now.

**Comment by AnnCherianA** [comment]
@JesniJ also mention if it's not seen on the website

**Comment by JesniJ** [comment]
I have compared it with the website in system view , and issue not exists there .

**Comment by AnnCherianA** [comment]
@JesniJ please verify this fix and update the result

**Comment by JesniJ** [comment]
The fix is verified in chrome browser.
Unnecessary spaces were removed from the bible reading pane .

![WhatsApp Image 2023-05-12 at 11 19 01 AM (1)](https://github.com/Bridgeconn/VachanOnline-v2/assets/102143707/f99d15e2-bff5-42de-8af8-1e43905eaf4b)

![WhatsApp Image 2023-05-12 at 11 19 01 AM](https://github.com/Bridgeconn/VachanOnline-v2/assets/102143707/69dcacbb-880c-4c89-b07a-43fc1cd1e967)

![WhatsApp Image 2023-05-12 at 11 19 00 AM](https://github.com/Bridgeconn/VachanOnline-v2/assets/102143707/190e06fb-a82c-4f59-acdf-0b2bb1bbfcb7)

As the issue is fixed moving this issue to done.
