### ISSUE TITLE
Audio Bible language is not changing

### ISSUE THREAD

**Issue by selvabenz** [Bridgeconn/VachanOnline-v2#320]
Audio Bible language is not changing when the language is changed. This happens in both mobile and desktop browsers. Chrome browser was used for the test on both devices.
_The steps_ 
1. Click the small audio Bible (speaker) icon on the top right corner
2. Play it from the player at the bottom 
3. It plays a current language  
4. Change the language in the text form and it won't change the audio in the player
5. Change to a different chapter in a different language still it plays the old audio

Screenshot 
![Audio Bible language is not changing](https://github.com/Bridgeconn/VachanOnline-v2/assets/121541505/1e77ac9a-198b-421a-af67-25a2ed669ad8)

**Comment by JesniJ** [comment]
Tested in chrome browser
Steps followed in testing :
1.Open bible reading page 
2. Click speaker icon from top 
3. audio plays in choosen language and book
4. change bible reading language 
5. click to play the audio 
6. audio plays in current selected language
Here am attaching screenrecording for the same. 

https://github.com/Bridgeconn/VachanOnline-v2/assets/102143707/6207b77b-3232-48a4-aaff-8dee4e34fdbf

Test results are verified and documented , therefore moving this issue to done.
