### ISSUE TITLE
Hindi Language selected on the language dropdown on refresh

### ISSUE THREAD

**Issue by VineethaVi** [Bridgeconn/VachanOnline-v2#349]
Steps to recreate
1. Open the website and select a bible say English ESV.
2. Refresh the page
3. Open the Version Dropdown
**Observation:** The Bible selected is still English ESV as it now stores it in the local storage now but in the dropdown it shows the Hindi language accordian open
![image](https://github.com/Bridgeconn/VachanOnline-v2/assets/12570574/0e333e39-749a-4d05-9199-dfa430c8d4ac)

**Exptected:** On opening the versin dropdown it should show open the  same language accordian as the one selected

**Comment by AnnCherianA** [comment]
@VineethaVi please test this issue and share the feedback

**Comment by AnnCherianA** [comment]
Please remember to test on mobile browser also and check the behaviour

**Comment by VineethaVi** [comment]
Test Result 

Selected Dogri from language dropdown
Selected Mathew from book dropdown
Refreshed the page
opened the language dropdown
showing the selected language Dogri

It is working fine and testing done on chrome.

![refresh](https://github.com/Bridgeconn/VachanOnline-v2/assets/132653333/bb714a88-be76-4394-8ba7-52888f156eec)

**Comment by VineethaVi** [comment]
Moving to QA Review

**Comment by VineethaVi** [comment]
Moving back to QA to edit the test result

**Comment by VineethaVi** [comment]
Moving to Done
