### ISSUE TITLE
Mobile View : Audio bible flash message not available for a second

### ISSUE THREAD

**Issue by VineethaVi** [Bridgeconn/VachanOnline-v2#350]
Steps
1. Open the browser in the mobile and open John1 
2. Open the Audio bible in the drawer and select a OBT Bible like Bommala 
**Observation** The message meant for the Desktop is shown for a second before the dropdown selects the first availalble book
In the desktop as the audio bible doesnt have a dedicated book dropdown and is controlled by the Book dropdown in the left panel the below message is shown if the Audio Bible is not found
![image](https://github.com/Bridgeconn/VachanOnline-v2/assets/12570574/02dfa2c8-8a7f-4888-8e89-2f8c7c3329d7)
**Exptected** As the mobile audio bible page has a dedicated book dropdown and the message is not valid there it should not show up as it shows the first available book instead.

**Comment by AnnCherianA** [comment]
@VineethaVi please test this issue and share your feedback

**Comment by VineethaVi** [comment]
Moving to QA Review

**Comment by VineethaVi** [comment]
Moving to Done
