### ISSUE TITLE
In parallel bible page, keep forward and backward arrow in (top or down) if parallel scroll is enabled 

### ISSUE THREAD

**Issue by JesniJ** [Bridgeconn/VachanOnline-v2#363]
**VO Mobile browser : Currently In parallel bible page, forward and  backward arrow exists in (top and bottom) even if the parallel scroll is enabled .**
![para1](https://github.com/Bridgeconn/VachanOnline-v2/assets/102143707/75e4e9d0-4b32-4642-96a4-27ba35e0536a)

-- Parallel scroll behaviour is like **if the user click forward in top** , then **automaticaly down part also goes forward** so keeping the arrows in top and bottom is not necessary when parallel scroll is enabled.
**Qa suggests to remove the arrows in one part.** 

**-- If the user disables the parallel scroll , that case both arrows requires in top and bottom**

**Comment by VineethaVi** [comment]
Test Result 

Selected English ESV from language dropdown 
Selected Genesis 1 from book dropdown 
Selected parallel bible from bottom bar 
It showing the forward arrow only at the top when the parallel scroll is enabled. 

It is working fine and testing done on google chrome in mobile.

![parllelscroll](https://github.com/Bridgeconn/VachanOnline-v2/assets/132653333/633e1132-9322-408c-a5bb-2742b66b29b1)

**Comment by VineethaVi** [comment]
Moving to Done.
