### ISSUE TITLE
Bible  language dropdown is retaining the last selected language on reopening it

### ISSUE THREAD

**Issue by JesniJ** [Bridgeconn/VachanOnline-v2#377]
Steps to track the issue : 
1. Open a bible reading page in English 
2. Open the language dropdown and click on Hindi and close it without selecting a version
3. Open the langauge dropdown again the old langauge selection Hindi is still open in the accordian

Here am attaching screen recording for the same :

https://github.com/Bridgeconn/VachanOnline-v2/assets/102143707/588b6bea-831b-4a78-b467-313121437eea

**Comment by VineethaVi** [comment]
Test Result : Tested on website

Selected English ESV from language dropdown
Selected Matthew 1 from book dropdown
opened the reading page
Clicked the Hindi language without  selecting the version 
closed the language dropdown
Selected the language dropdown, it showing the selected language English ESV.

It is working fine and testing done on chrome.

![new commentary](https://github.com/Bridgeconn/VachanOnline-v2/assets/132653333/2c719a0f-bee0-4e4a-866c-e41ab2f724c7)

**Comment by VineethaVi** [comment]
Test Result : Tested on Mobile browser
Selected English ESV from language dropdown
Selected Genesis 1 from book dropdown
opened the reading page
Clicked the Hindi language without selecting the version
closed the language dropdown
Selected the language dropdown, it showing the selected language English ESV.

It is working fine and testing done on chrome in mobile.

![IMG_20230717_065432](https://github.com/Bridgeconn/VachanOnline-v2/assets/132653333/a7682a55-0c93-4e25-ae56-6029896e040a)

**Comment by VineethaVi** [comment]
Moving to QA review

**Comment by VineethaVi** [comment]
Moving to Done
