### ISSUE TITLE
commentary intro, support partial commentary

### ISSUE THREAD

**Issue by Beenamol** [Bridgeconn/VachanOnline-v2#404]
1. Book name not getting updated in Partial Bibles
2. If commentary introduction available don't show 'No commentary available ...' message

**Comment by VineethaVi** [comment]
Test Result : Tested on website

Selected Psalms 1 in Kacchi ISV
opened reading page 
selected commentary from the left side
selected Kacchi KSN from the commentary dropdown
In the commentary  , it is showing the selected book name Psalms.
 Commentary available books not showing the message 'commentary not available'.

It is working fine and testing done on chrome.


![commentary](https://github.com/Bridgeconn/VachanOnline-v2/assets/132653333/ab98fa70-b9ff-4b51-96c1-8255c3204d10)



Selected Mark 1 in Koli,Kacchi 
selected Koli,kacchi KKSN from the commentary dropdown.
Koli,Kacchi KKSN commentary of the book Mark is not available. So, it is showing the message 'commentary not available for Mark 1'.


![nnnmsg](https://github.com/Bridgeconn/VachanOnline-v2/assets/132653333/72ebccc6-29e4-40fb-9363-982a717abe6f)


 Commentary available books not showing the message 'commentary not available'.

**Comment by VineethaVi** [comment]
Test Result : Tested on Mobile browser

Selected Proverbs 1 in Kukna ISV langauge
Opened reading page 
Selected commentary icon from the bottom 
opened Kukna KSN commentary , it is showing selected book name Proverbs.
Commentary available books not showing the message 'commentary not available'.

It is working fine and testing done on chrome in the Mobile.

![MicrosoftTeams-image (23)](https://github.com/Bridgeconn/VachanOnline-v2/assets/132653333/01433080-3bf8-494a-8c81-d9305ab240f5)

Selected Koli,Kacchi KKSN commentary from the commentary drop down 
Koli,Kacchi KKSN commentary not available for Proverbs. So, it is showing the message 'commentary not available'.


![MicrosoftTeams-image (27)](https://github.com/Bridgeconn/VachanOnline-v2/assets/132653333/852ac9fe-1278-4f44-a8ed-c8c04fc17ee9)

**Comment by VineethaVi** [comment]
Moving to QA review

**Comment by AnnCherianA** [comment]
> Test Result : Tested on website
> 
> Selected Psalms 1 in Kacchi ISV opened reading page selected commentary from the left side selected Kacchi KSN from the commentary dropdown In the commentary , it is showing the selected book name Psalms. Commentary available books not showing the message 'commentary not available'.
> 
> It is working fine and testing done on chrome.
> 
> ![commentary](https://user-images.githubusercontent.com/132653333/259727420-ab98fa70-b9ff-4b51-96c1-8255c3204d10.png)
> 
> Selected Mark 1 in Koli,Kacchi selected Koli,kacchi KKSN from the commentary dropdown. Koli,Kacchi KKSN commentary of the book Mark is not available. So, it is showing the message 'commentary not available for Mark 1'.
> 
> ![nnnmsg](https://user-images.githubusercontent.com/132653333/259731114-72ebccc6-29e4-40fb-9363-982a717abe6f.png)
> 
> Commentary available books not showing the message 'commentary not available'.

@Vineetha please make the changes we discussed and update the test result

**Comment by VineethaVi** [comment]
> > Test Result : Tested on website
> > Selected Psalms 1 in Kacchi ISV opened reading page selected commentary from the left side selected Kacchi KSN from the commentary dropdown In the commentary , it is showing the selected book name Psalms. Commentary available books not showing the message 'commentary not available'.
> > It is working fine and testing done on chrome.
> > ![commentary](https://user-images.githubusercontent.com/132653333/259727420-ab98fa70-b9ff-4b51-96c1-8255c3204d10.png)
> > Selected Mark 1 in Koli,Kacchi selected Koli,kacchi KKSN from the commentary dropdown. Koli,Kacchi KKSN commentary of the book Mark is not available. So, it is showing the message 'commentary not available for Mark 1'.
> > ![nnnmsg](https://user-images.githubusercontent.com/132653333/259731114-72ebccc6-29e4-40fb-9363-982a717abe6f.png)
> > Commentary available books not showing the message 'commentary not available'.
> 
> @vineetha please make the changes we discussed and update the test result

@AnnCherianA , I made the necessary changes above.

**Comment by VineethaVi** [comment]
Moving to Done
