### ISSUE TITLE
Videos are not loading on mobile browser

### ISSUE THREAD

**Issue by VineethaVi** [Bridgeconn/VachanOnline-v2#418]
Videos when selected from menu bar in the study mode are not loading and also noticed  from the landing page after refresh the website videos are not loading.

 Case-1

From landing page, first we select book and chapter in desired language. After clicking the start button , opened to study mode page. In the study mode page , select video icon from the menu bar . It is showing blank page , videos are not loading.

From landing page , select Genesis 1 in English ESV
                                  open study mode 
                                 select video from menu bar
                                  videos are not loading

Case - 2

From the landing , select book and chapter in desired language. click the Watch icon below the language and book dropdown. videos are not loading. It is showing blank page. 
Noticed : Videos are not loading after refreshing the website .

From landing page, select Genesis 1 in English ESV
select watch icon below the language and book dropdown
opened study mode page , videos are not loading. 

![MicrosoftTeams-image (35)](https://github.com/Bridgeconn/VachanOnline-v2/assets/132653333/2db394f3-3b69-4f3f-9893-ee4cd4645695)

**Comment by AnnCherianA** [comment]
@VineethaVi please   make the following update to this issue :
add the label regression
include the root cause analysis summary based on the discussion we had  from QA and dev side for this issue 
please include more steps which makes it  easy for the dev team  to understand the issue. Right now the description as we discussed in today's Vachan standup needs more info.

Thank you .

**Comment by AnnCherianA** [comment]
@VineethaVi mention the steps for the case where the videos do load

**Comment by VineethaVi** [comment]
As discussed in VO stand up , Root cause of  the issue : This issue occurred after fixing the issue 109 ,Add headers Old Testament and New Testament to differentiate between OT and NT books.
https://github.com/Bridgeconn/VachanOnline-v2/issues/109

**Comment by VineethaVi** [comment]
Test Result 

Case : 1

From landing page, selected English ESV from language dropdown
selected Genesis 1 from book dropdown
clicked start button
opened study mode page
selected videos icon from the menu bar.
Videos of Genesis 1 is showing in the selected language English.

It is working fine and testing done on chrome in the mobile .


![MicrosoftTeams-image (56)](https://github.com/Bridgeconn/VachanOnline-v2/assets/132653333/9bda9816-943d-4c5a-8312-e2acf7c527ff)
 



Case : 2

 From landing page , selected Hindi IRV from language dropdown.
selected  John 1 from book dropdown.
clicked Watch icon below the dropdowns.
opened to study mode page.
selected video icon from menu bar.
Videos of John chapter 1  is showing in the selected language Hindi.

It is working fine and testing done on chrome in the mobile.


![MicrosoftTeams-image (50)](https://github.com/Bridgeconn/VachanOnline-v2/assets/132653333/f2bc0f33-01f5-4d11-95d7-ee1ca98ca476)

**Comment by VineethaVi** [comment]
Moving to Done
