### ISSUE TITLE
Not able to change other book in Video Panel for Churahi : Mobile browser

### ISSUE THREAD

**Issue by VineethaVi** [Bridgeconn/VachanOnline-v2#473]
In mobile browser , not able to change the book  in video panel for some minority languages like Pahari,mahasu , Churahi , Gaddi , Pahari,kullu , Kangri , Mandeali.

Steps 
From landing page, select John  chapter 1 in English ESV.
Select video icon.
Select Churahi from language dropdown.
It is showing the message 'No videos available in churahi for John'
 Click book dropdown , it is not showing the book dropdown. Not able to change the book to Luke.

Video of Luke is available in these minority languages.

**Comment by VineethaVi** [comment]
Adding the screen recording



https://github.com/Bridgeconn/VachanOnline-v2/assets/132653333/d2be8275-7522-4a6f-b6b6-fe3ced0ae039

**Comment by AnnCherianA** [comment]
@VineethaVi please mention whether this happens only in Churahi or other minority languages .

**Comment by VineethaVi** [comment]
> @VineethaVi please mention whether this happens only in Churahi or other minority languages .

This happened only in minority languages Pahari,mahasu , Churahi , Gaddi , Pahari,kullu , Kangri , Mandeali , Churahi.

**Comment by VineethaVi** [comment]
@RevantCI  , will you link this issue to fix of this issue https://github.com/Bridgeconn/VachanOnline-v2/issues/400

**Comment by Beenamol** [comment]
- [ ] Recreating the bug(30 minutes)
- [ ] Fix bug ()
- [ ] Code Review()
- [ ] QA ()

**Comment by Beenamol** [comment]
I had call with Vineetha regarding this issue. But, we couldn't recreate this issue. I found that, its already fixed. 
So, **moved to Product Backlog**

**Comment by AnnCherianA** [comment]
@Beenamol  any idea which bug fixing would have led to the fix. Why is  the issue moved to Product Backlog ?

**Comment by VineethaVi** [comment]
> @Beenamol any idea which bug fixing would have led to the fix. Why is the issue moved to Product Backlog ?
   
In the  call we discussed , when I created the issue video for minority language  it is showing the message 'No videos available in churahi for John' for  books without video and not able to change the book from book dropdown. In the last sprint this issue is fixed by showing the video of unavailable books along with the issue https://github.com/Bridgeconn/VachanOnline-v2/issues/400

**Comment by Beenamol** [comment]
I had a call with Vineetha regarding this issue.  Actually, this issue was already fixed along with the issue #400 . In our call,  Vineetha has again checked this issue in her mobile and confirmed that its fixed.

**Comment by Beenamol** [comment]
Moved to QA

**Comment by VineethaVi** [comment]
Tested the issue , it is fixed .
For minority languages Pahari,mahasu , Churahi , Gaddi , Pahari,kullu , Kangri , Mandeali. showing the video of available books.

Adding the screenshot



![videochurahi](https://github.com/Bridgeconn/VachanOnline-v2/assets/132653333/c4460fb9-8fae-44a3-9039-7b2b57cf0ce7)

**Comment by VineethaVi** [comment]
This issue is fixed along with the issue https://github.com/Bridgeconn/VachanOnline-v2/issues/400 and the testing is passed.
So, closing this issue.


Moving to Done
