### ISSUE TITLE
In audio bible, for some languages which dont have content it shows the selected book number 

### ISSUE THREAD

**Issue by JesniJ** [Bridgeconn/VachanOnline-v2#478]
Issue Description : 
In audio bible, In these languages  Bommala , Dogri , Dommiri , Kachcha , Kongaru , Mayla marathi , Thakalika 
 If it open with bible reading in paralell screen  for other books which dont have content  it shows the selected  chapter number .

Steps to track the issue :
1. Select Genesis book , Eng-ESV  language and Open Study bible page from landing page
2.Select Audio bible from side bar
3. Change language in audio bible dropdown 
4. Select any langauge from these Bommala , Dogri , Dommiri , Kachcha , Kongaru , Mayla marathi , Thakalika 
5. It shows chapter number 

Here am attaching screenshots for the reference 
For Dogri Gensis 1 audio is not available , still showing chapter number 1
![Dogri_Genesis](https://github.com/Bridgeconn/VachanOnline-v2/assets/102143707/fbcaf779-df4e-49cb-8c0d-b97ef4e7ba4e)

For Bommala Gensis 1 audio is not available , still showing chapter number 1
![genesis_Bommala](https://github.com/Bridgeconn/VachanOnline-v2/assets/102143707/265afa98-f36f-47b4-be91-97d027333bdd)

**Comment by Poojanavgurukul** [comment]
Was unable to recreate the bug so had a call with @AnnCherianA  and was unable to recreate it with her as well.
Moving it to product backlog.

**Comment by JesniJ** [comment]
Tested and verified that , In audio bible, In these languages Bommala , Dogri , Dommiri , Kachcha , Kongaru , Mayla marathi , Thakalika If it open with bible reading in paralell screen for other books which dont have content it shows only 'alert message that content is not available ' , and the selected chapter number has been removed . 

Bommala Genesis :
![image](https://github.com/Bridgeconn/VachanOnline-v2/assets/102143707/09cccaac-4259-4340-987d-12ddad0cc076)

DOgri Genesis : 
![image](https://github.com/Bridgeconn/VachanOnline-v2/assets/102143707/8d750fc2-243a-4380-9b47-ee3b604a71ca)

Therefore moving this issue to done
