### ISSUE TITLE
Persian and Urdu language overlap to the bible stories dropdown : Mobile browser

### ISSUE THREAD

**Issue by VineethaVi** [Bridgeconn/VachanOnline-v2#536]
In bible stories, when selecting the language Persian and  Urdu from language dropdown that is overlapping to the bible stories dropdown and cannot read. Language not showing in the language dropdown. Language should show properly in the language dropdown.

Steps

Select Bible stories from the landing page.
Open to Bible stories , select language Persian and Urdu from language dropdown.
These two languages are overlapped to the bible stories dropdown.

Adding the screenshot of Urdu language

![Screenshot (655)](https://github.com/Bridgeconn/VachanOnline-v2/assets/132653333/c64a9719-8fa4-4d86-9b20-1373a3c4fd95)

Adding the screenshot of Persian language

![Screenshot (654)](https://github.com/Bridgeconn/VachanOnline-v2/assets/132653333/664dab3d-9eaf-4818-a97a-7b8fc2068c2c)

 This found in the phone , OppoA16e. Screen resolution of the phone : 1600 x 720

**Comment by Poojanavgurukul** [comment]
- [ ] Bug Fix (2 hours)
- [ ] unit testing ( 0.5 hour)
- [ ] QA ( )

**Comment by VineethaVi** [comment]
Moving to Done
