### ISSUE TITLE
Reference of verse of the day is not showing

### ISSUE THREAD

**Issue by VineethaVi** [Bridgeconn/VachanOnline-v2#545]
Sometime even at 100 % zoom the verse of the day reference  is not visible on Windows OS. But it appears on Linux OS.

Adding the screenshot 

![verse of the day new](https://github.com/Bridgeconn/VachanOnline-v2/assets/132653333/ced65e4f-303d-489c-8e96-ef03b557fc5d)

**Comment by Beenamol** [comment]
- [ ] Bug Fixing (15 Minutes) - (ATT: 15 Minutes)
- [ ] Code Review ()
- [ ] QA ()

**Comment by VineethaVi** [comment]
Testing is passed. 

- ​The reference to the verse of the day is shown.

Testing done on chrome.

Adding the screenshot

![versereference](https://github.com/Bridgeconn/VachanOnline-v2/assets/132653333/10aa70a8-0866-4010-a3c4-f3e3776fc5f5)

**Comment by VineethaVi** [comment]
Moving to Done.
