### ISSUE TITLE
Songs title is not changing to the selected multi language 

### ISSUE THREAD

**Issue by VineethaVi** [Bridgeconn/VachanOnline-v2#546]
The songs title is not changing to the selected multi language Hindi or English when changing the languages at the songs page.

**Steps to recreate**

- Open the songs page from landing page , it is opened in last selected multi language English.
- Select song from the drop-down
- change the English language to Hindi from multi-language option , the song title appears in the English language.

 
Expected Result : After selecting the language from multi-language option , the song title should  show in the selected language.

Adding the screenshot

![songnew](https://github.com/Bridgeconn/VachanOnline-v2/assets/132653333/cf90199e-8ec7-48f9-8c20-63c8799e9894)

**Comment by Beenamol** [comment]
- [ ] Fixing Bug (15 Minutes) (ATT - 10 Minutes)
- [ ] Code Review ()
- [ ] QA()

**Comment by VineethaVi** [comment]
Issue is fixed and testing is passed. It is working fine. 

- Song title is showing in the selected language from the multi language option.

 

**Adding the screenshot**

![songhl](https://github.com/Bridgeconn/VachanOnline-v2/assets/132653333/91602df0-d210-462f-aeb5-e2688b320b9f)




In the above screenshot, the selected language from the multi-language option is Hindi. So, the title is shown in the Hindi language.
