### ISSUE TITLE
Videos for Odia Mark 13 and 16 are not available, an notification message should appear

### ISSUE THREAD

**Issue by SeemaNandihal** [Bridgeconn/VachanOnline-v2#554]
The **videos** are organized by chapter for the book of Mark in Odia. Videos for chapters 13 and 16 are not available.
**Actual behavior:**
For Mark 13 and 16, the video pane is blank.
**Expected behaviour:**
For the FCBH (chapter wise) videos, a message saying "Videos not available for this chapter" should appear, when the video is unavailable for a specific chapter.

**Comment by Beenamol** [comment]
- [ ] Finding Videos not available books and chapter (15 Minutes)
- [ ] Adding not available message (2 Hours)
- [ ] Unit Testing (1 Hour)
- [ ] Code Review ()
- [ ] Code Review Fixes ()
- [ ] Writing Test Cases ()
- [ ] QA ()

**Comment by VineethaVi** [comment]
**Testing is passed.**

- The message 'No videos available 'is shown for unavailable videos.

**Testing Environment**

- Testing done on website and mobile browser.
- OS : Linux and Windows 11
- Browsers : Chrome.

**Adding the screenshot**


![odiavideo](https://github.com/Bridgeconn/VachanOnline-v2/assets/132653333/6dc3cb1b-3697-4eef-bd5e-be73ade2025b)

**Comment by VineethaVi** [comment]
Testing is passed. Moving this issue to Done.
