### ISSUE TITLE
OBS- Story titles as drop down- Website mobile-friendly

### ISSUE THREAD

**Issue by AnnCherianA** [Bridgeconn/VachanOnline-v2#77]
Story titles as drop down in the OBS

**Comment by AnnCherianA** [comment]
@savithasusannamark please test this issue

**Comment by savithasusannamark** [comment]
OBS story titles drop down is working fine
![obs](https://user-images.githubusercontent.com/83633509/124464646-13245f00-ddb2-11eb-9777-6858256284c2.jpg)
