### ISSUE TITLE
header is not showing properly in homepage in mobile

### ISSUE THREAD

**Issue by savithasusannamark** [Bridgeconn/VachanOnline-v2#81]
when we test vachan online in mobile browser (google), Header is not showing properly in homepage ex. language list, sign in is missing
![Screenshot_2021-06-04-14-00-07-537_com android chrome](https://user-images.githubusercontent.com/83633509/120981228-14537380-c795-11eb-8533-948ea4248fd1.jpg)

**Comment by AnnCherianA** [comment]
@savithasusannamark please test and share the result

**Comment by savithasusannamark** [comment]
header is looking  good, and when we click on the vachan logo it is taking to the bible read option.
![header2](https://user-images.githubusercontent.com/83633509/124463155-1880aa00-ddb0-11eb-9e61-3c6982b50784.jpg)

**Comment by AnuMonachan** [comment]
The V logo click leads to Read is fine, it is expected to do so.

**Comment by savithasusannamark** [comment]
Ok anu, issue is moved to done
